### ISSUE TITLE
Support versions of lambdas

### ISSUE THREAD

**Issue by mkotsur** [saksdirect/sbt-aws-lambda#22]
I found [lambdas versioning](http://docs.aws.amazon.com/lambda/latest/dg/versioning-intro.html) to be a pretty useful concept. Would you be interested to receive a pull request for that? Do you have any ides/preferences regarding how that should be modelled within the plugin?

**Comment by fiadliel** [comment]
From a brief glance at what it does, it seems like if we had an `awsLambdaVersion`, we could apply versioning to the scripts. Since many people may end up with version `0.1-SNAPSHOT`, and these lambda versions are immutable, we would need the ability to opt out of the feature; also, some people could have added a version to the end of the ARN, from using previous versions of the plugin without this feature.

First thought is to set the default version to `version.value`, but only if a `awsLambaVersioningEnabled` is set to `true`.

```scala
awsLambaVersion :=
  if (awsLambaVersioningEnabled.value)
    Some(version.value)
  else
    None
```

We can then manually override `awsLambdaVersion` if desired. When `awsLambaVersion` has a value, append `:[version]` to the ARN (handler name) for the function.

**Comment by marchub** [comment]
+1

**Comment by gheine** [comment]
Version support was added in 0.7.0
